name: navicat-keygen builds
on: 
  workflow_dispatch:

jobs:
  navicat-keygen-x86-win:
    runs-on: windows-latest
#     if: "startsWith(github.event.head_commit.message, '[build]')"
    steps:
      - name: Install dependencies
        run: |
          vcpkg install fmt:x86-windows-static
          vcpkg install openssl:x86-windows-static
          vcpkg install rapidjson:x86-windows-static
          vcpkg install keystone:x86-windows-static
          vcpkg install unicorn:x86-windows-static
      - name: Clone source
        uses: actions/checkout@v2
      - name: clone
        run: git clone https://notabug.org/doublesine/navicat-keygen.git

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: |
          vcpkg integrate install
          msbuild navicat-keygen.sln /p:Configuration=Release /p:Platform=x86
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keygen-x86-win.zip
          path: bin/x86-Release/*.exe

  navicat-keygen-x64-win:
    runs-on: windows-latest
#     if: "startsWith(github.event.head_commit.message, '[build]')"
    steps:
      - name: Install dependencies
        run: |
          vcpkg install fmt:x64-windows-static
          vcpkg install openssl:x64-windows-static
          vcpkg install rapidjson:x64-windows-static
          vcpkg install keystone:x64-windows-static
          vcpkg install unicorn:x64-windows-static
      - name: Clone source
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: |
          vcpkg integrate install
          msbuild navicat-keygen.sln /p:Configuration=Release /p:Platform=x64
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keygen-x64-win.zip
          path: bin/x64-Release/*.exe
          
  navicat-keygen-x64-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: apt-get install -y cmake libfmt-dev libssl-dev rapidjson-dev
      - name: Clone
        run: git clone -b linux --single-branch https://notabug.org/doublesine/navicat-keygen.git
      - name: Build
        run: |
          cd navicat-keygen
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -- -j4
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keygen-linux.zip
          path: build/*
