name: navicat-keygen builds
on: 
  workflow_dispatch:

env:
  REPO_URL: https://notabug.org/doublesine/navicat-keygen.git
  WIN_X86: true
  WIN_X64: false
  LINUX: false

jobs:
  navicat-keygen-x86-win:
    runs-on: windows-latest
    if: env.WIN_X86 == 'true'
    steps:
      - name: Install dependencies
        run: |
          vcpkg install fmt:x86-windows-static
          vcpkg install openssl:x86-windows-static
          vcpkg install rapidjson:x86-windows-static
          vcpkg install keystone:x86-windows-static
          vcpkg install unicorn:x86-windows-static
      - name: Clone source
        uses: actions/checkout@v2
        
      - name: Clone
        run: git clone -b windows --single-branch $REPO_URL

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: |
          cd navicat-keygen
          vcpkg integrate install
          msbuild navicat-keygen.sln /p:Configuration=Release /p:Platform=x86
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keygen-x86-win.zip
          path: ./*
#           path: bin/x86-Release/*.exe

  navicat-keygen-x64-win:
    runs-on: windows-latest
    if: env.WIN_X64 == 'true'
    steps:
      - name: Install dependencies
        run: |
          vcpkg install fmt:x64-windows-static
          vcpkg install openssl:x64-windows-static
          vcpkg install rapidjson:x64-windows-static
          vcpkg install keystone:x64-windows-static
          vcpkg install unicorn:x64-windows-static
      - name: Clone source
        uses: actions/checkout@v2

      - name: Clone
        run: git clone -b windows --single-branch $REPO_URL
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: |
          cd navicat-keygen
          vcpkg integrate install
          msbuild navicat-keygen.sln /p:Configuration=Release /p:Platform=x64
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keygen-x64-win.zip
          path: bin/x64-Release/*.exe
          
  navicat-keygen-linux:
    runs-on: ubuntu-latest
    if: env.LINUX == 'true'
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y cmake libfmt-dev libssl-dev rapidjson-dev
      - name: Clone
        run: git clone -b linux --single-branch $REPO_URL
      - name: Build
        run: |
          cd navicat-keygen
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -- -j4
          ls
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: navicat-keygen-linux.zip
          path: ./build/navicat-*
