name: NC-winx64 builds
on: 
  workflow_dispatch:

jobs:
  navicat-keygen-x64-win:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          vcpkg install fmt:x64-windows-static
          vcpkg install openssl:x64-windows-static
          vcpkg install rapidjson:x64-windows-static
          vcpkg install keystone:x64-windows-static
          vcpkg install unicorn:x64-windows-static
      - name: Clone source
        uses: actions/checkout@v2

      - name: Clone
        run: git clone -b windows --single-branch https://github.com/MatthewSama/NavicatCracker.git
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: |
          cd navicat-keygen
          vcpkg integrate install
          msbuild navicat-keygen.sln /p:Configuration=Release /p:Platform=x64
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: NavicatCracker-x64-win.zip
          path: ./NavicatCracker/bin/x64-Release/NEW/*.exe
